name: Events Demo 1
on: 
  pull_request:
    types: [opened, edited]
    branches: 
     - main # main branch
     - 'dev-*' #dev-new dev-this dev-another
     - 'feat/**' # feat/new #feat/new/button
     #developer
  push:
    branches: 
     - main # main branch
     - 'dev-*' #dev-new dev-this dev-another
     - 'feat/**' # feat/new #feat/new/button
     #developer
    #paths: # this workflow will be triggered when changes occur in this directory
    #  - '.github/workflows/*'
    paths-ignore:
      - '.github/workflows/*' #ignores changes made in this directory
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."